<html>
<head>
<title>Error Handling in JavaScript</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">JavaScript中的错误处理</h1>
<blockquote>原文：<a href="https://itnext.io/error-handling-in-javascript-3e444ccae117?source=collection_archive---------1-----------------------#2019-03-15">https://itnext.io/error-handling-in-javascript-3e444ccae117?source=collection_archive---------1-----------------------#2019-03-15</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><figure class="gl gn jo jp jq jr gh gi paragraph-image"><div class="gh gi jn"><img src="../Images/36d5f1602fceb28185b98002edb3fb8a.png" data-original-src="https://miro.medium.com/v2/resize:fit:1252/format:webp/1*B4jEYLg7oX3lcEH9C0YxaA.jpeg"/></div></figure><p id="2a6f" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">想想60-70年代的软件工程师，他们编写了一个代码，将火箭发射到轨道上，使用原始的编辑器和调试工具，没有我们现在所有的花哨功能，我钦佩他们处理可能的边缘情况的自律和专业精神，让意外成为预期。</p><p id="b423" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">我们大多数人，即开发人员，不会发射火箭，但我们的产品中仍有许多依赖关系，这些依赖关系可能会在许多方面破裂——数据库可能会失败，服务变得不可用，服务器超时或用户不会用预期的参数调用端点。因此，适当的错误处理是JavaScript开发人员睡个好觉的关键，尤其是在NodeJS环境中，因为未处理异常的影响比在浏览器中要大得多。</p><p id="a1f3" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">与bug相反，理论上异常不是你可以也应该避免的，而是应用程序生命周期的基本现象之一。不应该避免它，而是应该小心处理它，以使应用程序稳定，我称之为异常处理艺术，与应用程序逻辑的其余部分和谐而优雅。</p><p id="7da5" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">当异常发生时，应该正确地处理它，这意味着客户端应该收到友好的消息，并且应该将它记录在服务器上，以便您可以随时检查日志中可能出现的重复问题，这些问题需要改进。这提高了可维护性、可扩展性和可读性:</p><ul class=""><li id="c62d" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr kx ky kz la bi translated"><em class="lb">可维护性</em>允许容易地发现新的错误，而没有破坏当前功能或引入新的错误或增加技术债务的风险。</li><li id="8e6e" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated"><em class="lb">可扩展性</em>允许程序增长，在不破坏功能的情况下实现新的或改变现有的逻辑，并利用代码的可重用性。</li><li id="27f8" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated"><em class="lb">可读性</em>是关于阅读和理解代码目的的难易程度，这对于发现bug或未测试好的代码的效率至关重要。</li></ul></div><div class="ab cl lh li hu lj" role="separator"><span class="lk bw bk ll lm ln"/><span class="lk bw bk ll lm ln"/><span class="lk bw bk ll lm"/></div><div class="ij ik il im in"><p id="e4dd" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">在进入示例之前，让我们确保了解一些基础知识。我强调了JavaScript中的四种错误类型:</p><ol class=""><li id="db78" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr lo ky kz la bi translated"><em class="lb">语法错误</em>发生在解释时，它们被认为是bug，永远无法正确处理，因为代码从定义上来说就是错误的:</li></ol><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="a210" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">2.<em class="lb">程序错误</em>，也是bug。例如，试图读取<em class="lb">未定义的</em>的一个属性——这可以通过添加一个条件语句来改进这种特殊情况下的代码来避免。</p><p id="bc6b" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">3.<strong class="jw ir">运行时错误被称为异常</strong>，在执行过程中发生:</p><ul class=""><li id="cc78" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr kx ky kz la bi translated">无效的用户输入</li><li id="96e3" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">无法连接到数据库</li><li id="302b" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">系统内存不足</li><li id="67d5" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">等等..</li></ul><p id="e4f1" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">所有正确编写的程序都应该处理运行时错误，只要处理了异常，它们就不一定表明有bug或严重的问题。例如，运行时可能抛出一个<em class="lb">文件未找到</em>异常，这可能意味着必须首先创建文件。</p><p id="cb3d" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">4.<em class="lb">逻辑错误</em>是指开发人员在程序的逻辑上犯了错误，并且没有返回预期的结果。这类错误是最难追踪的，因为它们依赖于领域需求。</p><figure class="lp lq lr ls gt jr gh gi paragraph-image"><div role="button" tabindex="0" class="lw lx di ly bf lz"><div class="gh gi lv"><img src="../Images/93fde5e90adc2e8dcc0dd703be00fc5b.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*j1kRuqvznG4pyjWatfcmyQ.png"/></div></div></figure><p id="9bc4" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">未正确处理的运行时错误是一个缺陷。例如，如果运行时试图连接到数据库，但它得到一个没有注册处理程序的<code class="fe ma mb mc md b">NetworkError</code>，那么程序将崩溃，这就是程序错误——连接失败是运行时错误，但处理失败是程序错误。</p><p id="8e1e" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">一般来说，应该避免在一个集中的地方处理错误——每个逻辑部分都应该自己处理可能的失败，并根据失败的原因做出响应，但是在异常没有适当的处理程序的情况下，拥有一个集中的处理程序是有用的，它的唯一目的是为开发人员记录异常。我们将进一步研究如何在浏览器、NodeJs和Express中处理未捕获的异常。</p><blockquote class="me mf mg"><p id="f722" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated"><strong class="jw ir">总是创建应用程序错误的层次结构。</strong></p><p id="4bd7" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated">为应用程序提供可扩展的、全面的异常处理使得处理故障变得更加容易。</p></blockquote><p id="e505" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">也可以在几个堆栈级别处理相同的错误，例如，当较低的函数与异常无关，只是将错误传播到调用函数时，调用函数可能是唯一知道如何处理它的函数，但这并不意味着您应该在堆栈的顶层报告所有错误，因为单个函数无法知道异常发生的上下文或具体发生了什么。</p><p id="53bb" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">根据经验，<code class="fe ma mb mc md b">catch</code>应该只处理那些我们期望看到的错误，其余的应该用<code class="fe ma mb mc md b">throw</code>语句进一步传播。错误<code class="fe ma mb mc md b">name</code>用于定义当前级别是否会出现错误。</p><p id="b4cd" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">在NodeJS中传递错误有四种基本方法</p><ul class=""><li id="7c1e" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr kx ky kz la bi translated"><code class="fe ma mb mc md b">throw</code>错误(使其成为<em class="lb">异常</em>)。</li><li id="0d13" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">将错误传递给一个<em class="lb">回调</em>，这个函数专门用于处理错误和异步操作的结果</li><li id="5fb3" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">将错误传递给<em class="lb">拒绝</em>承诺功能</li><li id="b4ba" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">在EventEmitter上发出一个<code class="fe ma mb mc md b">"error"</code>事件</li></ul><h2 id="9417" class="mk ml iq bd mm mn mo dn mp mq mr dp ms kf mt mu mv kj mw mx my kn mz na nb nc bi translated">1.尝试..捕捉..最后施工</h2><p id="f306" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated">在执行代码之前不可能检查有效性条件的情况下，这种构造是必要的，例如<code class="fe ma mb mc md b">JSON.parse</code>不能预先检查字符串的正确性:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><ul class=""><li id="77fa" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr kx ky kz la bi translated">运行时执行<code class="fe ma mb mc md b">try</code>段中的代码，如果没有错误，它将跳过<code class="fe ma mb mc md b">catch</code>段，转到下一条语句。</li><li id="df77" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr kx ky kz la bi translated">如果出现错误，<code class="fe ma mb mc md b">try</code>部分的代码执行被中断，运行时直接跳转到带有<code class="fe ma mb mc md b">err</code>参数的<code class="fe ma mb mc md b">catch</code>处理程序，它保存了错误的详细信息。</li></ul><p id="09f3" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">有两个时刻值得一提:</p><ol class=""><li id="5522" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr lo ky kz la bi translated">上面的结构能够通过正确编写的代码只捕捉运行时发生的操作错误，而不是作为bug的程序员错误(如缺少右括号)。</li><li id="b9de" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr lo ky kz la bi translated">它只处理同步代码，下面的代码不起作用:</li></ol><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="a21e" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">这里你可以看到我们使用了一个<code class="fe ma mb mc md b">throw</code>操作符来抛出一个由<em class="lb"> ajax </em>函数返回的错误对象，并且我们在自定义条件下手动抛出<code class="fe ma mb mc md b">Error</code>对象。<strong class="jw ir">这两种情况都不会发生</strong>，因为在抛出错误的时候，<code class="fe ma mb mc md b">try/catch</code>语句已经执行完毕。回调由NodeJS直接调用，没有会导致应用程序崩溃的<code class="fe ma mb mc md b">try</code>部分。</p><h2 id="e1de" class="mk ml iq bd mm mn mo dn mp mq mr dp ms kf mt mu mv kj mw mx my kn mz na nb nc bi translated">2.NodeJS错误-第一次回调</h2><p id="3bff" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated">NodeJS通常使用回调模式，如果在执行过程中遇到错误，该错误将作为回调的第一个参数传递:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><ol class=""><li id="4721" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr lo ky kz la bi translated"><strong class="jw ir">回调的第一个参数是为错误对象保留的。</strong>如果出现错误，将由第一个也是唯一的<code class="fe ma mb mc md b">err</code>参数返回。</li><li id="a1b3" class="ks kt iq jw b jx lc kb ld kf le kj lf kn lg kr lo ky kz la bi translated"><strong class="jw ir">回调的第二个参数是为任何成功的响应数据保留的。</strong>如果没有错误发生，<code class="fe ma mb mc md b">err</code>将被设置为空，任何成功的数据将在第二个参数中返回。</li></ol><h2 id="fb21" class="mk ml iq bd mm mn mo dn mp mq mr dp ms kf mt mu mv kj mw mx my kn mz na nb nc bi translated"><strong class="ak"> <em class="ni">错误和异常的区别。</em> </strong></h2><p id="2f0b" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated">错误是<code class="fe ma mb mc md b">Error</code>类的一个实例，它可以作为参数传递给另一个函数，也可以被抛出。该错误在被抛出时成为一个异常。在JavaScript中，抛出任何东西都是可能的，不仅是<code class="fe ma mb mc md b">Error</code>对象，但不建议这样做，因为在这种情况下，异常不会保存一条可能有用的信息，如名称、消息或调用堆栈:</p><pre class="lp lq lr ls gt nj md nk nl aw nm bi"><span id="af6f" class="mk ml iq md b gy nn no l np nq">throw new Error('something bad happened');</span></pre><p id="e1a0" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">但是您也可以创建一个<code class="fe ma mb mc md b">Error</code>而不抛出它:</p><pre class="lp lq lr ls gt nj md nk nl aw nm bi"><span id="6c5b" class="mk ml iq md b gy nn no l np nq">callback(new Error('something bad happened'));</span></pre><p id="8dcf" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">这在Node.js中更常见，因为大多数错误都是异步的。正如我们将看到的，需要从同步函数中<code class="fe ma mb mc md b">catch</code>出一个错误是非常罕见的。</p><h2 id="e813" class="mk ml iq bd mm mn mo dn mp mq mr dp ms kf mt mu mv kj mw mx my kn mz na nb nc bi translated">3.承诺.拒绝</h2><p id="4492" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated"><code class="fe ma mb mc md b">Promise</code>是保持其状态的特殊对象。最初，它处于<em class="lb">等待</em>或<em class="lb">等待</em>的状态，然后<em class="lb">完成</em>(成功完成)或<em class="lb">拒绝</em>(发生错误)。</p><p id="3433" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">我不会详细讨论承诺，只是提到您可以为<code class="fe ma mb mc md b">fulfilled</code>和/或<code class="fe ma mb mc md b">rejected</code>状态添加两种类型的回调:</p><pre class="lp lq lr ls gt nj md nk nl aw nm bi"><span id="ac9f" class="mk ml iq md b gy nn no l np nq">promise.then(onFulfilled, onRejected)</span></pre><p id="d7fa" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">也可以只使用<code class="fe ma mb mc md b">.catch(onRejected)</code>而不是<code class="fe ma mb mc md b">.then(null, onRejected)</code>来添加错误处理程序，其工作方式相同。</p><p id="2271" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">同步<code class="fe ma mb mc md b">throw</code>语句作为<code class="fe ma mb mc md b">Promise</code>主体中的<code class="fe ma mb mc md b">reject</code>调用相应的回调函数:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><h2 id="b9db" class="mk ml iq bd mm mn mo dn mp mq mr dp ms kf mt mu mv kj mw mx my kn mz na nb nc bi translated">4.处理EventEmitter中的错误事件</h2><p id="efc6" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated">EventEmitter以一种特殊的方式处理名为<code class="fe ma mb mc md b">error</code>的事件:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="53c0" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">如果<code class="fe ma mb mc md b">error</code>事件发生在某个地方，并且它没有处理程序，那么EventEmitter会生成一个异常。因此，<code class="fe ma mb mc md b">emit</code>看似无害，将退出节点进程。</p><p id="97cb" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">作为最佳实践，应该始终为 <code class="fe ma mb mc md b"><strong class="jw ir">error</strong></code> <strong class="jw ir">事件</strong>添加<strong class="jw ir">监听器。</strong></p></div><div class="ab cl lh li hu lj" role="separator"><span class="lk bw bk ll lm ln"/><span class="lk bw bk ll lm ln"/><span class="lk bw bk ll lm"/></div><div class="ij ik il im in"><p id="9feb" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">让我们看一些应用程序中未处理错误的影响的例子。</p><p id="b8cf" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">我估计还是录个短视频例子比较好:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="nr lu l"/></div></figure><p id="57a7" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">在本例中，索引URL的逻辑如下:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="d5a6" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">所以<code class="fe ma mb mc md b">collection.findOne()</code>有<code class="fe ma mb mc md b">then</code>处理程序，但是没有<code class="fe ma mb mc md b">catch</code>块来处理<em class="lb">拒绝</em>承诺的状态。</p><p id="8c8d" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated"><code class="fe ma mb mc md b">Promises</code>应该总是有<code class="fe ma mb mc md b">catch</code>或<code class="fe ma mb mc md b">throw(null, onRejectedCallback)</code>来处理拒绝:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="nr lu l"/></div></figure><p id="47d8" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">此外，对于<code class="fe ma mb mc md b">async/await</code>,我们可以并且应该始终使用<code class="fe ma mb mc md b">try/catch</code>块:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><h1 id="2f80" class="ns ml iq bd mm nt nu nv mp nw nx ny ms nz oa ob mv oc od oe my of og oh nb oi bi translated">如何正确处理未捕获的异常</h1><p id="1f81" class="pw-post-body-paragraph ju jv iq jw b jx nd jz ka kb ne kd ke kf nf kh ki kj ng kl km kn nh kp kq kr ij bi translated">让我们看看如何处理一个未捕获的异常，以及如何在浏览器和NodeJS环境中处理它们。</p><p id="6eb0" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">强烈反对⚠️尝试从以下处理程序给出的意外错误中恢复！</p><ol class=""><li id="34b0" class="ks kt iq jw b jx jy kb kc kf ku kj kv kn kw kr lo ky kz la bi translated">一个<strong class="jw ir">浏览器</strong>有一个特殊的属性<code class="fe ma mb mc md b">window.error</code>，允许给它分配一个函数，这个函数将接收一个错误消息，当前的URL和行号，在那里抛出一个异常:</li></ol><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="645a" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">您不应该使用这种结构来恢复程序，在大多数情况下，这在这个阶段是不可能的，而只是向开发人员报告事件。</p><p id="a014" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">2.在<strong class="jw ir"> NodeJS </strong>中有一个process对象，它是一个EventEmitter，可以发布一个事件。我们可以订阅带有<code class="fe ma mb mc md b">process.on("uncaughtException")</code>的事件，并且我们可以传递一个回调来处理这个异常。在捕捉到这个未捕捉到的异常的情况下，进程不会终止，我们必须手动完成。处理程序应该只用于记录异常和终止进程，因为没有办法跟踪每个异常的原因并安全地恢复。</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="caf6" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">这种方法只对同步代码起作用，如果你有一个承诺拒绝，这个代码就不起作用。目前，未处理的承诺拒绝不会终止流程，但在将来，流程会崩溃。</p><p id="c11b" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated"><code class="fe ma mb mc md b">process</code>对象有另一个名为<code class="fe ma mb mc md b">unhandledRejection</code>的事件，应该用于异步异常。</p><blockquote class="me mf mg"><p id="3108" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated"><strong class="jw ir">从不从未捕获的异常中恢复</strong></p><p id="d12f" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated">永远不要尝试为基本的<code class="fe ma mb mc md b"><em class="iq">Error</em></code>类型实现一个无所不包的处理程序。这从来都不是一个好主意，因为它会混淆已经发生的事情，破坏代码的可维护性和可扩展性。在调试实际问题上浪费大量时间的风险，甚至是在一个简单的错误上。还要注意不要过度概括我们的异常处理程序</p></blockquote><p id="31f7" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">3.在<strong class="jw ir"> Express </strong>中，您可以拥有一个中央错误中间件功能，该功能必须添加到所有其他中间件功能的最后:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="1aa3" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">它应该有四个参数，第一个是<code class="fe ma mb mc md b">err</code>参数。异常将通过它传递。为了能够将一个异常传递给这个中间件，您应该将它作为一个参数传递给<code class="fe ma mb mc md b">next()</code>回调函数:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="fcbc" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">如果有一个集中的错误记录逻辑，这是非常有用的，您必须在一个地方更改它，但是请记住，它将忽略Express之外的所有内容。这就是为什么我们必须正确处理未处理的异常和未捕获的拒绝。</p><p id="aa62" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">可以创建一个异步错误捕获函数，它将包装中间件来解决重复的<code class="fe ma mb mc md b">try/catch</code>或<code class="fe ma mb mc md b">.catch</code>块，并处理Express应用程序中的所有异步错误:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="266a" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">现在，我们可以用它来包装应用程序中的所有中间件:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="9cdc" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">为了使上面的wrap函数更具可读性，让我们把它变得更详细一点，并把它转换成<code class="fe ma mb mc md b">async/await</code>版本:</p><figure class="lp lq lr ls gt jr"><div class="bz fp l di"><div class="lt lu l"/></div></figure><p id="78c7" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">这里的问题是，你必须记住把你所有的中间件都包装在这个<em class="lb">包装</em>函数中，这也使得代码有点嘈杂。相反，你可以使用一个<a class="ae oj" href="https://www.npmjs.com/package/express-async-errors" rel="noopener ugc nofollow" target="_blank"> express-async-errors </a> NPM模块，它在运行时对所有的路由处理程序进行猴子修补。</p><blockquote class="me mf mg"><p id="74b2" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated"><strong class="jw ir">记录一切</strong></p><p id="ed9e" class="ju jv lb jw b jx jy jz ka kb kc kd ke mh kg kh ki mi kk kl km mj ko kp kq kr ij bi translated">当然，这种做法不仅仅适用于异常，但是如果有一件事情应该<strong class="jw ir">总是</strong>被记录，那么它就是异常。跟踪我们的异常是非常重要的，这样我们就可以回顾发生了什么，并调查是否有什么事情看起来不对劲。正确的日志消息可以直接为开发人员指出问题的原因，为他们节省大量时间。</p></blockquote><figure class="lp lq lr ls gt jr gh gi paragraph-image"><div role="button" tabindex="0" class="lw lx di ly bf lz"><div class="gh gi lv"><img src="../Images/925a13369f5f24cee667923a887bd899.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*LXj8gnQTZ0Rg0hVLp_WREg.png"/></div></div></figure><p id="d498" class="pw-post-body-paragraph ju jv iq jw b jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ij bi translated">异常是程序员生活的一部分。学习如何在你的程序中正确地处理它们以平衡代码质量和可维护性是很重要的。如果上面展示的例子和常见的实践能让你在处理错误案例时更有信心，那就太好了。</p></div></div>    
</body>
</html>