<html>
<head>
<title>How to throw an exception in a callback in Java</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">如何在Java的回调中抛出异常</h1>
<blockquote>原文：<a href="https://itnext.io/how-to-throw-an-exception-in-a-callback-in-java-ebcf65bac35e?source=collection_archive---------7-----------------------#2019-07-29">https://itnext.io/how-to-throw-an-exception-in-a-callback-in-java-ebcf65bac35e?source=collection_archive---------7-----------------------#2019-07-29</a></blockquote><div><div class="fc ii ij ik il im"/><div class="in io ip iq ir"><div class=""/><div class=""><h2 id="5659" class="pw-subtitle-paragraph jr it iu bd b js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ki dk translated">将异步回调转换为同步<strong class="ak">方法调用</strong></h2></div><figure class="kk kl km kn gu ko gi gj paragraph-image"><div role="button" tabindex="0" class="kp kq di kr bf ks"><div class="gi gj kj"><img src="../Images/746a1400433a672f55f9b112c84aa56a.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*-uHRalV-UboIHKnEbtqVrA.png"/></div></div></figure><p id="dd3c" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">这有点奇怪，在一切都是异步的世界里，我需要编写同步代码，甚至抛出异常。但是对于向Java实现的遗留OOP系统添加新特性来说，这是正常的。最近，我在这种非常健壮并且遵循OOP设计模式的系统上做了一些工作。</p><p id="e011" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">我的任务之一是在遗留系统中添加对新打印机品牌的支持，在这个任务中我应该实现几个类和接口。通过在遗留系统上抛出异常和几个方法签名抛出<code class="fe lr ls lt lu b">PrintingException</code>来处理失败。例如，有一个名为<code class="fe lr ls lt lu b">printText</code>的方法返回void，如果这个方法可以成功打印什么都没发生并且不返回任何东西(void)，但是如果在打印过程中出现问题，我应该抛出一个<code class="fe lr ls lt lu b">PrintingException</code>(这篇文章中的所有代码都不是真实的，只是示例代码)</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure><p id="2cf8" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">新的打印机提供了用于通信的Java API，它由监听器(Java世界中回调的通用名称)工作，在<code class="fe lr ls lt lu b">printText</code>方法中，我应该调用打印机Java API并为其设置一个回调，但是我不能在<code class="fe lr ls lt lu b">onFailure</code>或<code class="fe lr ls lt lu b">onTimeout</code>回调方法中抛出异常:</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure><p id="068c" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">回调适用于异步世界，但不适用于这种同步系统。因为调用<code class="fe lr ls lt lu b">printText</code>的父方法将它包装成一个try-catch，并通过检查<code class="fe lr ls lt lu b">PrintingException</code>的类型来处理失败:</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure><p id="45bf" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">我知道这个设计不好，但我不能改变它。为了使同步方法调用的异步回调能够抛出异常，我需要同步它。一种选择是使用同步块，并在Java中使用<code class="fe lr ls lt lu b">wait()</code>和<code class="fe lr ls lt lu b">notify()</code>机制。为了实现这个目标，我定义了一个名为<code class="fe lr ls lt lu b">PrintTask</code>的类:</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure><p id="5bb5" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">通过调用<code class="fe lr ls lt lu b">getResult</code>方法，当前线程停止，直到得到结果或抛出异常。我们在<code class="fe lr ls lt lu b">PrintListener</code>回调方法中调用<code class="fe lr ls lt lu b">setResult</code>方法:</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure><p id="abaf" class="pw-post-body-paragraph kv kw iu kx b ky kz jv la lb lc jy ld le lf lg lh li lj lk ll lm ln lo lp lq in bi translated">除了定义一个新类和使用同步块和<code class="fe lr ls lt lu b">wait()</code>和<code class="fe lr ls lt lu b">notify()</code>机制，还有另一种方法，使用<code class="fe lr ls lt lu b">CompletableFuture</code>类。但是<code class="fe lr ls lt lu b">CompletableFuture</code>有一个问题，因为在<code class="fe lr ls lt lu b">CompletableFuture </code>中导致失败的异常总是被包装在CompletionException中，我们应该从CompletionException中提取它并重新抛出它:</p><figure class="kk kl km kn gu ko"><div class="bz fq l di"><div class="lv lw l"/></div></figure></div></div>    
</body>
</html>